
import os
BOT_TOKEN=os.getenv("BOT_TOKEN","")
ADMIN_IDS=os.getenv("ADMIN_IDS","")
SUPPORT_USERNAME=os.getenv("SUPPORT_USERNAME","@JanKug")
BINANCE_PAY_ID=os.getenv("BINANCE_PAY_ID","")
BINANCE_PAY_API_KEY=os.getenv("BINANCE_PAY_API_KEY","")
BINANCE_PAY_SECRET=os.getenv("BINANCE_PAY_SECRET","")
BINANCE_PAY_CURRENCY=os.getenv("BINANCE_PAY_CURRENCY","USDT")
